(() => {
"use strict";
const $=s=>document.querySelector(s),canvas=$("#canvas"),ctx=canvas.getContext("2d"),W=960,H=600,keys={},audio={};
const scolds=["Tá vendo? Tá limpo igual tua cara!","Isso pra você tá limpo?","Você acha que essa casa se limpa sozinha?","Eu mandei fazer isso faz uma hora!","Enquanto você morar debaixo do meu teto...","Eu não sou sua empregada!","Se eu tiver que fazer, você vai ver!","Eu sabia que você tava enrolando!"];
const calls=["MENINO! Já terminou?","Eu tô ouvindo silêncio demais...","Tá fazendo o quê aí?","Não me faça ir até aí!","Essa louça não vai se lavar sozinha!","Eu mandei varrer essa casa!","Menino, eu vou contar até três!"];
const taskDefs={
sweep:{name:"Varrer a sala",short:"VARRER",x:245,y:220,d:3,icon:"🧹",act:"Varrendo...",anim:"sweep"},
bath:{name:"Limpar o banheiro",short:"LIMPAR",x:815,y:155,d:4,icon:"🧽",act:"Limpando banheiro...",anim:"clean"},
toys:{name:"Guardar brinquedos",short:"GUARDAR",x:530,y:180,d:3.5,icon:"🧸",act:"Guardando brinquedos...",anim:"clean"},
ingredients:{name:"Pegar ingredientes",short:"PEGAR",x:685,y:385,d:2.5,icon:"🥕",act:"Pegando ingredientes...",anim:"clean"},
cook:{name:"Preparar a comida",short:"COZINHAR",x:855,y:385,d:5,icon:"🍳",act:"Cozinhando...",anim:"cook"},
dishes:{name:"Lavar a louça",short:"LAVAR",x:775,y:500,d:4,icon:"🍽️",act:"Lavando louça...",anim:"wash"},
area:{name:"Limpar a área",short:"LIMPAR",x:250,y:500,d:4,icon:"🪣",act:"Limpando área...",anim:"clean"},
yard:{name:"Limpar o quintal",short:"VARRER",x:105,y:500,d:4.5,icon:"🍂",act:"Juntando as folhas...",anim:"sweep"},
trash:{name:"Tirar o lixo",short:"TIRAR LIXO",x:280,y:540,d:3,icon:"🗑️",act:"Tirando lixo...",anim:"clean"},
organize:{name:"Organizar objetos",short:"ORGANIZAR",x:530,y:180,d:4,icon:"📦",act:"Organizando...",anim:"clean"},
kitchen:{name:"Limpar a cozinha",short:"LIMPAR",x:720,y:535,d:5,icon:"✨",act:"Limpando cozinha...",anim:"clean"},
surprise:{name:"Surpresa: arrumar a cama",short:"ARRUMAR",x:500,y:360,d:5,icon:"🛏️",act:"Arrumando cama...",anim:"clean"}};
const phases=[{name:"ARRUMANDO A CASA",time:120,drain:.62,momSpeed:58,tasks:["sweep","bath","toys"]},{name:"HORA DO ALMOÇO",time:105,drain:.82,momSpeed:72,tasks:["ingredients","cook","dishes","area"]},{name:"A MÃE TÁ BRAVA",time:95,drain:1.08,momSpeed:86,tasks:["yard","trash","organize","kitchen","surprise"]}];
const walls=[{x:0,y:0,w:960,h:18},{x:0,y:582,w:960,h:18},{x:0,y:0,w:18,h:600},{x:942,y:0,w:18,h:600},{x:320,y:18,w:14,h:135},{x:320,y:215,w:14,h:165},{x:320,y:445,w:14,h:137},{x:640,y:18,w:14,h:100},{x:640,y:180,w:14,h:200},{x:640,y:445,w:14,h:137},{x:334,y:285,w:115,h:14},{x:515,y:285,w:125,h:14},{x:654,y:285,w:105,h:14},{x:825,y:285,w:117,h:14}];
const furniture=[
{x:65,y:70,w:155,h:62,c:"#3f83b5",label:"SOFÁ",kind:"sofa"},{x:122,y:275,w:82,h:45,c:"#9b6842",label:"MESA",kind:"table"},
{x:385,y:65,w:175,h:80,c:"#e89b67",label:"CAMA",kind:"bed"},{x:575,y:45,w:45,h:105,c:"#875d47",label:"ARMÁRIO",kind:"wardrobe"},
{x:700,y:55,w:92,h:50,c:"#79c9d6",label:"CHUVEIRO",kind:"shower"},{x:840,y:70,w:48,h:65,c:"#eee",label:"WC",kind:"toilet"},
{x:680,y:320,w:82,h:52,c:"#87a96b",label:"GELADEIRA",kind:"fridge"},{x:825,y:320,w:92,h:50,c:"#9aa3ad",label:"FOGÃO",kind:"stove"},
{x:710,y:455,w:145,h:43,c:"#65a394",label:"PIA",kind:"sink"},{x:875,y:465,w:45,h:80,c:"#b9824d",label:"ARMÁRIO",kind:"cabinet"},
{x:385,y:325,w:175,h:82,c:"#bd9bd1",label:"CAMA",kind:"bed"},{x:565,y:440,w:52,h:100,c:"#8b654d",label:"ARMÁRIO",kind:"wardrobe"},
{x:220,y:430,w:65,h:42,c:"#82b9bf",label:"TANQUE",kind:"tank"}];
let phase=0,state="menu",player,mom,tasks=[],timeLeft=0,patience=100,doing=null,doProgress=0,last=0,totalElapsed=0,totalDone=0,callText="",callTimer=0,nextCall=12,redAlerted=false,failStage="",failHold=0,lastPatienceState=0,countSequence=0,toastTimer=0;

function show(id){document.querySelectorAll(".screen").forEach(x=>x.classList.remove("active"));$("#"+id).classList.add("active")}
function beep(type){try{const A=window.AudioContext||window.webkitAudioContext;audio.ctx=audio.ctx||new A();const o=audio.ctx.createOscillator(),g=audio.ctx.createGain();o.connect(g);g.connect(audio.ctx.destination);o.type=type==="alert"?"sawtooth":"sine";o.frequency.value=type==="alert"?180:type==="done"?660:type==="win"?880:120;g.gain.setValueAtTime(.065,audio.ctx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.ctx.currentTime+.18);o.start();o.stop(audio.ctx.currentTime+.18)}catch(e){}}
function startPhase(n){phase=n;const p=phases[n];tasks=p.tasks.map(id=>({...taskDefs[id],id,done:false}));timeLeft=p.time;patience=100;doing=null;doProgress=0;redAlerted=false;lastPatienceState=0;failStage="";player={x:270,y:545,r:13,speed:175,dir:"up",walk:0,moving:false};mom={x:55,y:180,r:14,speed:p.momSpeed,target:{x:150,y:180},think:0,walk:0};state="playing";nextCall=8+Math.random()*9;callTimer=0;countSequence=0;$("#alert").style.display="none";$("#taskToast").style.display="none";updateHud();show("game")}
function circleRect(x,y,r,q){return x+r>q.x&&x-r<q.x+q.w&&y+r>q.y&&y-r<q.y+q.h}
function blocked(x,y,r){return walls.some(q=>circleRect(x,y,r,q))||furniture.some(q=>circleRect(x,y,r,q))}
function move(ent,dx,dy,dt){let nx=ent.x+dx*dt,ny=ent.y+dy*dt,moved=false;if(!blocked(nx,ent.y,ent.r)){ent.x=nx;moved=true}if(!blocked(ent.x,ny,ent.r)){ent.y=ny;moved=true}if(moved)ent.walk=(ent.walk||0)+dt*10;return moved}
function nearestTask(){let best=null,bd=72;for(const t of tasks)if(!t.done){const d=Math.hypot(player.x-t.x,player.y-t.y);if(d<bd){best=t;bd=d}}return best}
function patienceIndex(){return patience>68?0:patience>40?1:patience>18?2:3}
function patienceInfo(){return [["🟢 TRANQUILA","#43c86f"],["🟡 DESCONFIADA","#f1c84b"],["🟠 IRRITADA","#f08b35"],["🔴 MENINO!!!","#e52d4f"]][patienceIndex()]}
function updateHud(){const p=phases[phase],done=tasks.filter(t=>t.done).length;$("#phaseLabel").textContent="FASE "+(phase+1);$("#phaseName").textContent=p.name;$("#time").textContent=fmt(timeLeft);$("#timeBox").className="time"+(timeLeft<=10?" danger-time":timeLeft<=30?" warning":"");const pi=patienceInfo(),idx=patienceIndex();$("#patienceState").textContent=pi[0];$("#patienceBar").style.width=patience+"%";$("#patienceBar").style.background=pi[1];if(idx!==lastPatienceState){$("#patienceBox").classList.remove("state-flash");void $("#patienceBox").offsetWidth;$("#patienceBox").classList.add("state-flash");lastPatienceState=idx}$("#missionList").innerHTML=tasks.map(t=>'<li class="'+(t.done?"done":"")+'">'+(t.done?"☑":"☐")+" "+t.name+"</li>").join("");$("#taskCount").textContent=done+"/"+tasks.length;$("#taskBar").style.width=(done/tasks.length*100)+"%"}
function fmt(s){s=Math.max(0,Math.ceil(s));return String(Math.floor(s/60)).padStart(2,"0")+":"+String(s%60).padStart(2,"0")}
function validTarget(){for(let i=0;i<20;i++){const p={x:40+Math.random()*880,y:40+Math.random()*520};if(!blocked(p.x,p.y,mom.r))return p}return{x:60,y:180}}
function momAI(dt){const chase=patience<=18||(phase===2&&patience<35);if(chase){const dx=player.x-mom.x,dy=player.y-mom.y,d=Math.hypot(dx,dy)||1;mom.speed=phases[phase].momSpeed*(patience<=18?1.62:1.22);move(mom,dx/d*mom.speed,dy/d*mom.speed,dt)}else{mom.speed=phases[phase].momSpeed;mom.think-=dt;if(mom.think<=0||Math.hypot(mom.x-mom.target.x,mom.y-mom.target.y)<20){mom.target=validTarget();mom.think=2+Math.random()*3}const dx=mom.target.x-mom.x,dy=mom.target.y-mom.y,d=Math.hypot(dx,dy)||1;move(mom,dx/d*mom.speed,dy/d*mom.speed,dt)}if(Math.hypot(player.x-mom.x,player.y-mom.y)<32&&patience<=18)beginFail()}
function beginFail(){if(state!=="playing")return;state="scolding";failStage="approach";failHold=0;doing=null;$("#progressBox").style.display="none";callText=scolds[Math.floor(Math.random()*scolds.length)];beep("fail")}
function finishTask(t){t.done=true;doing=null;doProgress=0;totalDone++;patience=Math.min(100,patience+10);beep("done");$("#taskToast").style.display="block";toastTimer=1.7;updateHud();if(tasks.every(x=>x.done)){state="complete";beep("win");$("#resultTime").textContent=fmt(timeLeft);$("#resultTasks").textContent=tasks.length+"/"+tasks.length;$("#resultPatience").textContent=Math.round(patience)+"%";setTimeout(()=>{if(phase===2){$("#totalTime").textContent=fmt(totalElapsed);$("#totalTasks").textContent=totalDone;show("victory");state="victory"}else show("phaseComplete")},900)}}
function startCounting(){countSequence=1;callText="UM...";callTimer=1.2}
function updateCounting(dt){if(!countSequence)return;callTimer-=dt;if(callTimer<=0){if(countSequence===1){countSequence=2;callText="DOIS...";callTimer=1.5}else if(countSequence===2){countSequence=3;callText="...";callTimer=.8}else{callText="TRÊS!";callTimer=1.4;countSequence=0;patience=Math.max(0,patience-7)}}}
function update(dt){if(toastTimer>0){toastTimer-=dt;if(toastTimer<=0)$("#taskToast").style.display="none"}if(state==="playing"){totalElapsed+=dt;timeLeft-=dt;patience=Math.max(0,patience-phases[phase].drain*dt);let dx=(keys.ArrowRight||keys.d?1:0)-(keys.ArrowLeft||keys.a?1:0),dy=(keys.ArrowDown||keys.s?1:0)-(keys.ArrowUp||keys.w?1:0);player.moving=!!(dx||dy);if(dx||dy){let d=Math.hypot(dx,dy);dx/=d;dy/=d;if(Math.abs(dx)>Math.abs(dy))player.dir=dx>0?"right":"left";else player.dir=dy>0?"down":"up";move(player,dx*player.speed,dy*player.speed,dt)}momAI(dt);nextCall-=dt;if(countSequence)updateCounting(dt);else{callTimer=Math.max(0,callTimer-dt);if(nextCall<=0){callText=calls[Math.floor(Math.random()*calls.length)];callTimer=3;if(callText.includes("contar até três"))setTimeout(()=>{if(state==="playing")startCounting()},2200);nextCall=10+Math.random()*12}}
const near=nearestTask();$("#interaction").style.display=near?"block":"none";if(near)$("#interaction").textContent="[E] "+near.short;if(keys.e&&near){if(doing!==near){doing=near;doProgress=0}doProgress+=dt;$("#progressBox").style.display="block";$("#progressText").textContent=near.act;$("#progressBar").style.width=Math.min(100,doProgress/near.d*100)+"%";if(doProgress>=near.d)finishTask(near)}else{doing=null;doProgress=0;$("#progressBox").style.display="none"}
if(patience<=18&&!redAlerted){redAlerted=true;beep("alert");$("#alert").style.display="block";$("#canvasWrap").classList.add("shake");setTimeout(()=>{$("#alert").style.display="none";$("#canvasWrap").classList.remove("shake")},2200)}if(timeLeft<=0)beginFail();updateHud()}
else if(state==="scolding"){const dx=player.x-mom.x,dy=player.y-mom.y,d=Math.hypot(dx,dy)||1;if(failStage==="approach"){if(d>47)move(mom,dx/d*135,dy/d*135,dt);else{failStage="lecture";failHold=2.7;callTimer=9}}else{failHold-=dt;if(failHold<=0){$("#scoldText").textContent=callText;show("gameOver");state="over"}}}}
function rr(x,y,w,h,r,fill,stroke){ctx.beginPath();ctx.roundRect(x,y,w,h,r);if(fill){ctx.fillStyle=fill;ctx.fill()}if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=2;ctx.stroke()}}
function room(x,y,w,h,name,c,pattern){ctx.fillStyle=c;ctx.fillRect(x,y,w,h);ctx.save();ctx.globalAlpha=.09;ctx.strokeStyle="#243044";ctx.lineWidth=1;if(pattern==="tile"){for(let xx=x;xx<x+w;xx+=28){ctx.beginPath();ctx.moveTo(xx,y);ctx.lineTo(xx,y+h);ctx.stroke()}for(let yy=y;yy<y+h;yy+=28){ctx.beginPath();ctx.moveTo(x,yy);ctx.lineTo(x+w,yy);ctx.stroke()}}else{for(let yy=y+12;yy<y+h;yy+=24){ctx.beginPath();ctx.moveTo(x,yy);ctx.lineTo(x+w,yy);ctx.stroke()}}ctx.restore();rr(x+10,y+8,Math.max(72,name.length*8),24,8,"#ffffffb8");ctx.fillStyle="#243044";ctx.font="bold 12px sans-serif";ctx.fillText(name,x+19,y+25)}
function drawFurniture(f){ctx.save();ctx.shadowColor="#0004";ctx.shadowBlur=5;ctx.shadowOffsetY=3;rr(f.x,f.y,f.w,f.h,7,f.c,"#27364a");ctx.shadowColor="transparent";if(f.kind==="sofa"){rr(f.x+8,f.y+9,f.w-16,25,7,"#63a8d1");ctx.strokeStyle="#d6efff";ctx.beginPath();ctx.moveTo(f.x+f.w/2,f.y+10);ctx.lineTo(f.x+f.w/2,f.y+34);ctx.stroke()}if(f.kind==="bed"){rr(f.x+10,f.y+8,f.w-20,f.h-16,6,"#f6dfbd");rr(f.x+18,f.y+10,50,24,6,"#fff");ctx.fillStyle=f.c;ctx.fillRect(f.x+10,f.y+45,f.w-20,25)}if(f.kind==="stove"){ctx.fillStyle="#222";for(const dx of[22,65])for(const dy of[16,36]){ctx.beginPath();ctx.arc(f.x+dx,f.y+dy,7,0,7);ctx.fill()}if(doing&&doing.id==="cook"){ctx.fillStyle="#ff6b35";ctx.beginPath();ctx.arc(f.x+65,f.y+34,5+Math.sin(performance.now()/80)*3,0,7);ctx.fill()}}if(f.kind==="sink"){ctx.fillStyle="#d8f4f1";ctx.beginPath();ctx.ellipse(f.x+45,f.y+21,28,12,0,0,7);ctx.fill();ctx.strokeStyle="#444";ctx.beginPath();ctx.arc(f.x+45,f.y+8,12,3.2,6);ctx.stroke();if(doing&&doing.id==="dishes"){ctx.fillStyle="#79d9ff";for(let i=0;i<4;i++){ctx.beginPath();ctx.arc(f.x+85+i*8,f.y+12+Math.sin(performance.now()/100+i)*5,3,0,7);ctx.fill()}}}if(f.kind==="fridge"){ctx.strokeStyle="#e9f5e4";ctx.beginPath();ctx.moveTo(f.x,f.y+28);ctx.lineTo(f.x+f.w,f.y+28);ctx.stroke();ctx.fillStyle="#fff";ctx.fillRect(f.x+65,f.y+11,3,12)}if(f.kind==="toilet"){ctx.fillStyle="#fff";ctx.beginPath();ctx.ellipse(f.x+24,f.y+38,17,23,0,0,7);ctx.fill();rr(f.x+8,f.y+6,32,24,6,"#fff")}if(f.kind==="shower"){ctx.strokeStyle="#e8ffff";ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(f.x+18,f.y+10);ctx.lineTo(f.x+18,f.y+32);ctx.arc(f.x+31,f.y+32,13,3.1,6.2);ctx.stroke()}if(f.kind==="wardrobe"||f.kind==="cabinet"){ctx.strokeStyle="#d6b28f";ctx.beginPath();ctx.moveTo(f.x+f.w/2,f.y+5);ctx.lineTo(f.x+f.w/2,f.y+f.h-5);ctx.stroke();ctx.fillStyle="#f2c078";ctx.beginPath();ctx.arc(f.x+f.w/2-5,f.y+f.h/2,2,0,7);ctx.arc(f.x+f.w/2+5,f.y+f.h/2,2,0,7);ctx.fill()}ctx.restore()}
function dirty(id){return tasks.some(t=>t.id===id&&!t.done)}
function decor(){// sala
rr(78,160,175,72,10,"#e45757aa");ctx.fillStyle="#f7df74";ctx.fillRect(91,173,149,4);rr(235,62,55,34,5,"#263238");ctx.fillStyle="#86d4ef";ctx.fillRect(241,68,43,22);ctx.fillStyle="#5d4435";ctx.fillRect(235,100,55,12);
ctx.strokeStyle="#444";ctx.lineWidth=3;ctx.beginPath();ctx.arc(278,270,19,0,7);ctx.stroke();ctx.beginPath();ctx.moveTo(278,289);ctx.lineTo(278,325);ctx.stroke();for(let i=0;i<5;i++){ctx.beginPath();ctx.moveTo(278,270);ctx.lineTo(278+Math.cos(i*1.25)*18,270+Math.sin(i*1.25)*18);ctx.stroke()}
if(dirty("sweep")){ctx.fillStyle="#9b765a";for(const p of[[55,245],[225,190],[275,335],[90,340]]){ctx.beginPath();ctx.arc(p[0],p[1],5,0,7);ctx.fill()}ctx.fillStyle="#fff";ctx.fillRect(250,245,18,10);ctx.fillRect(55,320,15,9)}
if(dirty("toys")||dirty("organize")){ctx.font="22px serif";ctx.fillText("🧸",520,225);ctx.fillText("⚽",590,240);ctx.fillText("👕",440,235)}
// banheiro
ctx.fillStyle="#89c2d9";rr(675,205,70,38,5,"#f2fbff");ctx.fillStyle="#80c7d8";ctx.fillRect(680,190,60,9);ctx.fillStyle="#c8eef4";ctx.fillRect(680,110,55,60);ctx.strokeStyle="#fff";ctx.strokeRect(680,110,55,60);ctx.font="18px serif";ctx.fillText("🧴",900,230);ctx.fillText("🪣",860,240);if(dirty("bath")){ctx.fillStyle="#8c8b6870";for(const p of[[790,220],[880,190],[760,250],[900,150]]){ctx.beginPath();ctx.ellipse(p[0],p[1],12,6,.3,0,7);ctx.fill()}}
// cozinha
rr(785,390,120,42,7,"#d7a86e");ctx.fillStyle="#f4e7ce";ctx.beginPath();ctx.arc(810,411,9,0,7);ctx.arc(845,411,9,0,7);ctx.fill();ctx.fillStyle="#8d6748";for(const x of[795,880]){ctx.fillRect(x,432,5,28)}ctx.font="18px serif";ctx.fillText("🍳",885,440);ctx.fillText("🗑️",900,560);if(dirty("dishes")||dirty("kitchen")){ctx.font="19px serif";ctx.fillText("🍽️🍽️🍽️",755,450)}
// área/quintal
ctx.strokeStyle="#5b7350";ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(35,420);ctx.lineTo(295,420);ctx.stroke();for(const x of[70,145,220]){ctx.beginPath();ctx.moveTo(x,420);ctx.lineTo(x,455);ctx.stroke()}ctx.font="20px serif";ctx.fillText("👕",85,448);ctx.fillText("🩳",160,448);ctx.fillText("🪣",200,535);ctx.fillText("🧹",250,550);ctx.fillStyle="#6b4d32";ctx.fillRect(35,470,22,70);ctx.fillStyle="#4d9b50";ctx.beginPath();ctx.arc(46,460,35,0,7);ctx.fill();if(dirty("yard")){ctx.font="17px serif";for(const p of[[70,520],[130,550],[175,485],[295,510]])ctx.fillText("🍂",p[0],p[1])}
}
function drawTask(t,near){if(t.done)return;const pulse=3+Math.sin(performance.now()/220)*3;ctx.save();ctx.strokeStyle=near===t?"#fff36b":"#ffd34e";ctx.lineWidth=near===t?5:3;ctx.setLineDash([7,5]);ctx.beginPath();ctx.arc(t.x,t.y,24+pulse,0,7);ctx.stroke();ctx.setLineDash([]);ctx.font="25px serif";ctx.textAlign="center";ctx.fillText(t.icon,t.x,t.y+8);ctx.textAlign="left";ctx.restore()}
function drawKid(p){const bob=p.moving?Math.sin(p.walk)*2:Math.sin(performance.now()/500)*.7,doingNow=doing&&keys.e,arm=Math.sin(performance.now()/100)*5;ctx.save();ctx.translate(p.x,p.y+bob);ctx.fillStyle="#0003";ctx.beginPath();ctx.ellipse(0,18,15,6,0,0,7);ctx.fill();ctx.strokeStyle="#24252a";ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(-5,9);ctx.lineTo(-7+(p.moving?Math.sin(p.walk)*4:0),20);ctx.moveTo(5,9);ctx.lineTo(7-(p.moving?Math.sin(p.walk)*4:0),20);ctx.stroke();ctx.strokeStyle="#f2b98b";ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(-9,-2);ctx.lineTo(-15,doingNow?arm:8);ctx.moveTo(9,-2);ctx.lineTo(15,doingNow?-arm:8);ctx.stroke();rr(-11,-10,22,23,7,"#2d8dcc","#18364d");ctx.fillStyle="#f2b98b";ctx.beginPath();ctx.arc(0,-20,11,0,7);ctx.fill();ctx.fillStyle="#35271f";ctx.beginPath();ctx.arc(0,-25,11,3.2,6.3);ctx.lineTo(9,-19);ctx.lineTo(4,-24);ctx.lineTo(0,-20);ctx.lineTo(-5,-25);ctx.fill();ctx.fillStyle="#222";ctx.beginPath();ctx.arc(p.dir==="left"?-5:p.dir==="right"?5:-3,-20,1.3,0,7);ctx.arc(p.dir==="left"?0:p.dir==="right"?8:3,-20,1.3,0,7);ctx.fill();ctx.fillStyle="#fff";ctx.fillRect(-10,19,8,4);ctx.fillRect(3,19,8,4);if(doingNow&&doing.anim==="sweep"){ctx.strokeStyle="#8c5a35";ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(12,-4);ctx.lineTo(22+arm,23);ctx.stroke();ctx.fillStyle="#e4b84b";ctx.fillRect(14+arm,20,18,5)}ctx.restore()}
function drawMom(p){const idx=patienceIndex(),bob=Math.sin(p.walk)*1.5;ctx.save();ctx.translate(p.x,p.y+bob);ctx.fillStyle="#0003";ctx.beginPath();ctx.ellipse(0,19,17,6,0,0,7);ctx.fill();ctx.strokeStyle="#54382d";ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(-6,10);ctx.lineTo(-7,22);ctx.moveTo(6,10);ctx.lineTo(7,22);ctx.stroke();ctx.strokeStyle="#d99570";ctx.beginPath();ctx.moveTo(-11,-3);ctx.lineTo(-17,8);ctx.moveTo(11,-3);ctx.lineTo(17,idx>=2?-3:8);ctx.stroke();rr(-13,-11,26,26,8,idx===3?"#d52e4c":"#e35d7a","#7a2941");ctx.fillStyle="#d99570";ctx.beginPath();ctx.arc(0,-23,12,0,7);ctx.fill();ctx.fillStyle="#4a2e24";ctx.beginPath();ctx.arc(0,-27,13,3.1,6.3);ctx.arc(10,-28,7,0,7);ctx.fill();ctx.strokeStyle="#3b2520";ctx.lineWidth=2;ctx.beginPath();if(idx<2){ctx.moveTo(-7,-25);ctx.lineTo(-2,-25);ctx.moveTo(2,-25);ctx.lineTo(7,-25)}else{ctx.moveTo(-7,-27);ctx.lineTo(-2,-24);ctx.moveTo(2,-24);ctx.lineTo(7,-27)}ctx.stroke();ctx.beginPath();if(idx===0)ctx.arc(0,-18,4,0,3.1);else if(idx===1)ctx.moveTo(-4,-18),ctx.lineTo(4,-18);else ctx.arc(0,-16,4,3.2,6.1);ctx.stroke();ctx.font="bold 24px sans-serif";ctx.textAlign="center";if(idx===1)ctx.fillText("?",0,-46);if(idx===2)ctx.fillText("!",0,-46);if(idx===3)ctx.fillText("!!!",0,-46);ctx.textAlign="left";ctx.restore()}
function bubble(text,big=false){const w=big?360:310,h=big?66:50,x=Math.max(8,Math.min(W-w-8,mom.x-w/2)),y=Math.max(8,mom.y-(big?105:88));rr(x,y,w,h,13,"#fff","#27364a");ctx.fillStyle="#202635";ctx.font=(big?"bold 17px":"bold 14px")+" sans-serif";ctx.textAlign="center";const words=text.split(" ");let line="",lines=[];for(const word of words){if(ctx.measureText(line+word).width>w-28){lines.push(line);line=""}line+=word+" "}lines.push(line);lines.slice(0,2).forEach((l,i)=>ctx.fillText(l,x+w/2,y+22+i*20));ctx.textAlign="left";ctx.fillStyle="#fff";ctx.beginPath();ctx.moveTo(Math.max(x+25,Math.min(x+w-25,mom.x)),y+h);ctx.lineTo(mom.x,y+h+12);ctx.lineTo(Math.max(x+45,Math.min(x+w-10,mom.x+18)),y+h);ctx.fill()}
function draw(){if(!["playing","scolding","complete"].includes(state))return;ctx.clearRect(0,0,W,H);room(18,18,302,362,"SALA","#f5d98a","wood");room(334,18,306,267,"QUARTO","#efc7d4","wood");room(654,18,288,267,"BANHEIRO","#bfe7ec","tile");room(654,299,288,283,"COZINHA","#cfe8c4","tile");room(334,299,306,283,"QUARTO","#ddc9e9","wood");room(18,394,302,188,"ÁREA / QUINTAL","#9ed08b","tile");decor();ctx.fillStyle="#694b39";walls.forEach(q=>{ctx.fillRect(q.x,q.y,q.w,q.h);ctx.fillStyle="#916d52";ctx.fillRect(q.x+2,q.y+2,Math.max(0,q.w-4),Math.max(0,q.h-4));ctx.fillStyle="#694b39"});furniture.forEach(drawFurniture);const near=state==="playing"?nearestTask():null;tasks.forEach(t=>drawTask(t,near));drawKid(player);drawMom(mom);if(callTimer>0||state==="scolding"&&failStage==="lecture")bubble(callText,state==="scolding")}
function loop(ts){const dt=Math.min(.033,(ts-last)/1000||0);last=ts;update(dt);draw();requestAnimationFrame(loop)}
addEventListener("keydown",e=>{const k=e.key.length===1?e.key.toLowerCase():e.key;keys[k]=true;if(["ArrowUp","ArrowDown","ArrowLeft","ArrowRight"," "].includes(e.key))e.preventDefault()});addEventListener("keyup",e=>{const k=e.key.length===1?e.key.toLowerCase():e.key;keys[k]=false});
$("#playBtn").onclick=()=>{totalElapsed=0;totalDone=0;startPhase(0)};$("#nextBtn").onclick=()=>startPhase(phase+1);$("#retryBtn").onclick=()=>startPhase(phase);$("#menuBtn").onclick=()=>{state="menu";show("menu")};$("#victoryMenuBtn").onclick=()=>{state="menu";show("menu")};requestAnimationFrame(loop);
})();