(()=>{"use strict";
const $=s=>document.querySelector(s),C=$("#canvas"),X=C.getContext("2d"),W=960,H=600,K={},A={};
const scolds=["Tá vendo? Tá limpo igual tua cara!","Isso pra você tá limpo?","Você acha que essa casa se limpa sozinha?","Eu mandei fazer isso faz uma hora!","Enquanto você morar debaixo do meu teto...","Eu não sou sua empregada!","Se eu tiver que fazer, você vai ver!","Eu sabia que você tava enrolando!"];
const calls=["MENINO! Já terminou?","Eu tô ouvindo silêncio demais...","Tá fazendo o quê aí?","Não me faça ir até aí!","Essa louça não vai se lavar sozinha!","Eu mandei varrer essa casa!","Menino, eu não vou falar duas vezes!","Você acha que eu não tô vendo?","Cadê você?","Eu conheço suas manhas!","Quer que eu vá aí?","Eu vou contar até três!"];
const angry=["Cadê esse menino?","Eu sei que você tá enrolando!","Eu vou te achar!","Eu tô ouvindo seus passos!","Não corre dentro de casa!","Se quebrar alguma coisa, você vai pagar!"];
const T={sweep:{name:"Varrer a sala",short:"VARRER",x:245,y:220,d:3,icon:"🧹",act:"Varrendo..."},bath:{name:"Limpar o banheiro",short:"LIMPAR",x:815,y:155,d:4,icon:"🧽",act:"Limpando..."},toys:{name:"Guardar brinquedos",short:"GUARDAR",x:530,y:180,d:3.5,icon:"🧸",act:"Guardando..."},ingredients:{name:"Pegar ingredientes",short:"PEGAR",x:685,y:385,d:2.5,icon:"🥕",act:"Pegando..."},cook:{name:"Preparar a comida",short:"COZINHAR",x:855,y:385,d:5,icon:"🍳",act:"Cozinhando..."},dishes:{name:"Lavar a louça",short:"LAVAR",x:775,y:500,d:4,icon:"🍽️",act:"Lavando..."},area:{name:"Limpar a área",short:"LIMPAR",x:250,y:500,d:4,icon:"🪣",act:"Limpando..."},yard:{name:"Limpar o quintal",short:"VARRER",x:105,y:500,d:4.5,icon:"🍂",act:"Juntando folhas..."},trash:{name:"Tirar o lixo",short:"TIRAR LIXO",x:280,y:540,d:3,icon:"🗑️",act:"Tirando lixo..."},organize:{name:"Organizar objetos",short:"ORGANIZAR",x:530,y:180,d:4,icon:"📦",act:"Organizando..."},kitchen:{name:"Limpar a cozinha",short:"LIMPAR",x:720,y:535,d:5,icon:"✨",act:"Limpando..."},surprise:{name:"Surpresa: arrumar a cama",short:"ARRUMAR",x:500,y:360,d:5,icon:"🛏️",act:"Arrumando..."}};
const P=[{name:"ARRUMANDO A CASA",time:120,drain:.6,mom:57,event:24,tasks:["sweep","bath","toys"]},{name:"HORA DO ALMOÇO",time:105,drain:.82,mom:70,event:17,tasks:["ingredients","cook","dishes","area"]},{name:"A MÃE TÁ BRAVA",time:95,drain:1.05,mom:84,event:12,tasks:["yard","trash","organize","kitchen","surprise"]}];
const walls=[{x:0,y:0,w:960,h:18},{x:0,y:582,w:960,h:18},{x:0,y:0,w:18,h:600},{x:942,y:0,w:18,h:600},{x:320,y:18,w:14,h:135},{x:320,y:215,w:14,h:165},{x:320,y:445,w:14,h:137},{x:640,y:18,w:14,h:100},{x:640,y:180,w:14,h:200},{x:640,y:445,w:14,h:137},{x:334,y:285,w:115,h:14},{x:515,y:285,w:125,h:14},{x:654,y:285,w:105,h:14},{x:825,y:285,w:117,h:14}];
const furn=[{x:65,y:70,w:155,h:62,c:"#3f83b5",k:"sofa"},{x:122,y:275,w:82,h:45,c:"#9b6842",k:"table"},{x:385,y:65,w:175,h:80,c:"#e89b67",k:"bed"},{x:575,y:45,w:45,h:105,c:"#875d47",k:"wardrobe"},{x:700,y:55,w:92,h:50,c:"#79c9d6",k:"shower"},{x:840,y:70,w:48,h:65,c:"#eee",k:"toilet"},{x:680,y:320,w:82,h:52,c:"#87a96b",k:"fridge"},{x:825,y:320,w:92,h:50,c:"#9aa3ad",k:"stove"},{x:710,y:455,w:145,h:43,c:"#65a394",k:"sink"},{x:875,y:465,w:45,h:80,c:"#b9824d",k:"cabinet"},{x:385,y:325,w:175,h:82,c:"#bd9bd1",k:"bed"},{x:565,y:440,w:52,h:100,c:"#8b654d",k:"wardrobe"},{x:220,y:430,w:65,h:42,c:"#82b9bf",k:"tank"}];
const hides=[{x:225,y:95,label:"ATRÁS DO SOFÁ"},{x:605,y:125,label:"NO GUARDA-ROUPA"},{x:605,y:505,label:"NO GUARDA-ROUPA"}];
const tools=[{id:"broom",name:"VASSOURA",icon:"🧹",x:275,y:535},{id:"cloth",name:"PANO",icon:"🧻",x:895,y:230},{id:"bucket",name:"BALDE",icon:"🪣",x:235,y:520},{id:"bag",name:"SACO DE LIXO",icon:"🗑️",x:290,y:520},{id:"sponge",name:"ESPONJA",icon:"🧽",x:900,y:510}];
const helps=[{id:"coffee",name:"CAFÉ",icon:"☕",x:705,y:405,e:40},{id:"cookie",name:"BISCOITO",icon:"🍪",x:610,y:235,e:22},{id:"watch",name:"RELÓGIO",icon:"⌚",x:420,y:230,time:8}];
const interactives=[{id:"tv",name:"ASSISTIR TV",x:265,y:78,kind:"distract"},{id:"bed",name:"DEITAR UM POUCO",x:470,y:110,kind:"distract"},{id:"fridge",name:"ABRIR GELADEIRA",x:720,y:350,kind:"fun"},{id:"fan",name:"LIGAR VENTILADOR",x:278,y:280,kind:"secret"},{id:"sink",name:"USAR TORNEIRA",x:775,y:480,kind:"water"}];
const req={sweep:"broom",bath:"bucket",dishes:"sponge",area:"cloth",yard:"broom",trash:"bag",kitchen:"cloth"};
const itemNames={broom:"🧹 VASSOURA",cloth:"🧻 PANO",bucket:"🪣 BALDE",bag:"🗑️ SACO DE LIXO",sponge:"🧽 ESPONJA"};
const nodes=[{x:270,y:180},{x:270,y:410},{x:360,y:180},{x:610,y:180},{x:680,y:180},{x:900,y:180},{x:610,y:410},{x:680,y:410},{x:900,y:410},{x:360,y:540},{x:610,y:540},{x:680,y:540},{x:280,y:540},{x:70,y:540},{x:70,y:350},{x:280,y:350}];
let phase=0,state="menu",pl,mom,tasks=[],time=0,pat=100,energy=100,noise=0,doing=null,prog=0,last=0,totalElapsed=0,totalDone=0,totalScore=0,score=0,combo=0,comboT=0,maxCombo=1,call="",callT=0,nextCall=10,red=false,failStage="",failT=0,lastPI=0,count=0,toastT=0,eventT=0,event=null,eventToastT=0,seen=0,alerts=0,stillT=0,runT=0,revisitT=0,rain=false,particles=[],stepT=0,lastRoom="",pendingPhase=0,equipped=null,picked=new Set(),usedHelp=new Set(),tempTasks=[],optionalTasks=[],secretUsed=new Set(),distraction=0,blackout=0,momPhone=0,slip=0,noiseCount=0,surpriseAdded=false,finaleDone=false,achT=0;
let save=loadSave();
function loadSave(){try{return Object.assign({bestScore:0,bestTime:0,unlocked:1,stars:[0,0,0],music:true,sfx:true,volume:.7,tutorial:false,plays:0,tasksDone:0,bestCombo:0,caught:0,achievements:[]},JSON.parse(localStorage.getItem("cqmtvSave")||"{}"))}catch(e){return{bestScore:0,bestTime:0,unlocked:1,stars:[0,0,0],music:true,sfx:true,volume:.7,tutorial:false,plays:0,tasksDone:0,bestCombo:0,caught:0,achievements:[]}}}
function saveIt(){try{localStorage.setItem("cqmtvSave",JSON.stringify(save))}catch(e){}}
function show(id){document.querySelectorAll(".screen").forEach(e=>e.classList.remove("active"));$("#"+id).classList.add("active")}
function beep(t){if(!save.sfx)return;try{const AC=window.AudioContext||window.webkitAudioContext;A.c=A.c||new AC();let o=A.c.createOscillator(),g=A.c.createGain();o.connect(g);g.connect(A.c.destination);o.type=t==="alert"?"sawtooth":"sine";o.frequency.value=t==="done"?680:t==="win"?900:t==="ring"?760:t==="bell"?520:t==="alert"?180:130;g.gain.setValueAtTime(.055*save.volume,A.c.currentTime);g.gain.exponentialRampToValueAtTime(.001,A.c.currentTime+.18);o.start();o.stop(A.c.currentTime+.18)}catch(e){}}
function audioUI(){$("#musicBtn").textContent="🎵 MÚSICA: "+(save.music?"ON":"OFF");$("#sfxBtn").textContent="🔊 EFEITOS: "+(save.sfx?"ON":"OFF");$("#volumeRange").value=Math.round(save.volume*100)}
function menuData(){audioUI();$("#achievements").innerHTML=save.achievements.length?"🏆 Conquistas: <b>"+save.achievements.length+"/5</b> &nbsp; • &nbsp; 🎮 Partidas: "+save.plays+" &nbsp; • &nbsp; 🔥 Combo: x"+save.bestCombo:"";$("#records").innerHTML="🏆 Melhor pontuação: <b>"+save.bestScore+"</b> &nbsp; • &nbsp; ⭐ "+save.stars.map((s,i)=>"F"+(i+1)+": "+s).join(" &nbsp; ");$("#phaseButtons").innerHTML=P.map((p,i)=>'<button data-p="'+i+'" '+(i>=save.unlocked?"disabled":"")+'>FASE '+(i+1)+'<br><small>'+p.name+'</small><br>'+(i>=save.unlocked?"🔒":"⭐".repeat(save.stars[i]||0))+"</button>").join("");document.querySelectorAll("#phaseButtons button:not(:disabled)").forEach(b=>b.onclick=()=>{totalElapsed=totalDone=totalScore=0;start(+b.dataset.p)})}
function start(n){pendingPhase=n;showIntro(n)}
function showIntro(n){phase=n;$("#introPhase").textContent="FASE "+(n+1);$("#introTitle").textContent=P[n].name;$("#introText").textContent=["Sua mãe mandou arrumar tudo antes que ela volte para conferir.","Ela está com fome. É melhor não enrolar.","Agora você realmente está encrencado."][n];$("#intro").classList.add("active")}
function beginPhase(n){phase=n;let p=P[n];save.plays++;saveIt();tasks=p.tasks.map(id=>({...T[id],id,done:false}));time=p.time;pat=energy=100;noise=score=combo=comboT=0;maxCombo=1;particles.length=0;equipped=null;picked=new Set();usedHelp=new Set();tempTasks=[];optionalTasks=[];secretUsed=new Set();distraction=blackout=momPhone=slip=noiseCount=0;surpriseAdded=false;finaleDone=false;if(Math.random()<.55)optionalTasks.push({id:"bonusbed",name:"BÔNUS: Arrumar a cama",x:500,y:360,d:3.5,icon:"🛏️",act:"Arrumando...",optional:true,done:false});doing=null;prog=0;red=false;lastPI=0;failStage="";pl={x:270,y:545,r:13,speed:175,dir:"up",walk:0,moving:false,hidden:false};mom={x:55,y:180,r:14,target:{x:150,y:180},pause:0,walk:0,path:[],lastSeen:null,search:0,investigate:null,seenCool:0};state="playing";nextCall=7+Math.random()*8;callT=count=0;eventT=P[n].event*(.75+Math.random()*.5);event=null;rain=false;seen=alerts=stillT=runT=revisitT=0;$("#alert").style.display=$("#taskToast").style.display="none";$("#pause").classList.remove("active");hud();show("game")}
function cr(x,y,r,q){return x+r>q.x&&x-r<q.x+q.w&&y+r>q.y&&y-r<q.y+q.h}
function blocked(x,y,r){return walls.some(q=>cr(x,y,r,q))||furn.some(q=>cr(x,y,r,q))}
function move(e,dx,dy,dt){let ok=false,nx=e.x+dx*dt,ny=e.y+dy*dt;if(!blocked(nx,e.y,e.r)){e.x=nx;ok=true}if(!blocked(e.x,ny,e.r)){e.y=ny;ok=true}if(ok)e.walk=(e.walk||0)+dt*10;return ok}
function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}
function nearTask(includeDone=false){let b=null,d=70;for(const t of tasks)if(includeDone||!t.done){let q=dist(pl,t);if(q<d){b=t;d=q}}return b}
function nearHide(){let b=null,d=55;for(const h of hides){let q=dist(pl,h);if(q<d){b=h;d=q}}return b}
function pidx(){return pat>68?0:pat>40?1:pat>18?2:3}
function pinfo(){return [["🟢 TRANQUILA","#43c86f"],["🟡 DESCONFIADA","#f1c84b"],["🟠 IRRITADA","#f08b35"],["🔴 MENINO!!!","#e52d4f"]][pidx()]}
function fmt(s){s=Math.max(0,Math.ceil(s));return String(Math.floor(s/60)).padStart(2,"0")+":"+String(s%60).padStart(2,"0")}
function hud(){let done=tasks.filter(t=>t.done).length,pi=pinfo(),idx=pidx();$("#itemHud").textContent="ITEM: "+(equipped?itemNames[equipped]:"—");let active=tasks.find(t=>!t.done);$("#stepHud").textContent=active?"ETAPA: "+taskHint(active):"ETAPA: finalize os extras";$("#phaseLabel").textContent="FASE "+(phase+1);$("#phaseName").textContent=P[phase].name;$("#time").textContent=fmt(time);$("#timeBox").className="time"+(time<=10?" danger-time":time<=30?" warning":"");$("#score").textContent=score;$("#combo").textContent=combo>1?"COMBO x"+combo:"";$("#energyBar").style.width=energy+"%";$("#noiseBar").style.width=noise+"%";$("#patienceState").textContent=pi[0];$("#patienceBar").style.width=pat+"%";$("#patienceBar").style.background=pi[1];if(idx!==lastPI){$("#patienceBox").classList.remove("state-flash");void $("#patienceBox").offsetWidth;$("#patienceBox").classList.add("state-flash");lastPI=idx}$("#missionList").innerHTML=[...tasks,...tempTasks,...optionalTasks].map(t=>'<li class="'+(t.done?"done ":"")+(t.optional?"optional":t.temp?"temp":"")+'">'+(t.done?"☑":"☐")+" "+t.name+"</li>").join("");$("#taskCount").textContent=done+"/"+tasks.length;$("#taskBar").style.width=done/tasks.length*100+"%"}
function taskHint(t){if(t.done)return "concluída";if(req[t.id]&&equipped!==req[t.id])return "pegue "+itemNames[req[t.id]];if(t.id==="bath"&&!t.filled)return "encha o balde na pia";if(t.id==="cook"&&!tasks.find(x=>x.id==="ingredients")?.done)return "pegue os ingredientes primeiro";return t.name}
function achievement(id,name){if(save.achievements.includes(id))return;save.achievements.push(id);saveIt();$("#achievementToast").textContent="🏆 CONQUISTA: "+name;$("#achievementToast").style.display="block";achT=3}
function say(s,t=3){call=s;callT=t}
function noiseAt(level,x=pl.x,y=pl.y){noise=Math.min(100,noise+level);if(level>=25)noiseCount++;if(noiseCount>=5)achievement("noise","EU OUVI ISSO!");if(level>=35||noise>65){mom.investigate={x,y};mom.search=4+phase*1.2;if(pidx()>=1)say("QUE BARULHO FOI ESSE?")}}
function lineClear(a,b){let steps=Math.ceil(dist(a,b)/12);for(let i=1;i<steps;i++){let x=a.x+(b.x-a.x)*i/steps,y=a.y+(b.y-a.y)*i/steps;if(blocked(x,y,6))return false}return true}
function visible(){return !pl.hidden&&dist(pl,mom)<(pidx()>=2?250:190)&&lineClear(pl,mom)}
function nearestNode(pos){let best=nodes[0],d=1e9;for(const n of nodes){let q=dist(pos,n);if(q<d){d=q;best=n}}return best}
function pathTo(target){let a=nearestNode(mom),b=nearestNode(target);if(a===b)return [target];let ai=nodes.indexOf(a),bi=nodes.indexOf(b),path=[];const adj=(i,j)=>dist(nodes[i],nodes[j])<210&&lineClear(nodes[i],nodes[j]);let q=[ai],prev=Array(nodes.length).fill(-1),seenN=new Set([ai]);while(q.length){let i=q.shift();if(i===bi)break;for(let j=0;j<nodes.length;j++)if(!seenN.has(j)&&adj(i,j)){seenN.add(j);prev[j]=i;q.push(j)}}if(prev[bi]!==-1||ai===bi){let cur=bi;while(cur!==ai){path.unshift(nodes[cur]);cur=prev[cur]}path.unshift(a)}path.push(target);return path}
function follow(target,speed,dt){if(!mom.path.length||dist(mom.path[mom.path.length-1],target)>45)mom.path=pathTo(target);let t=mom.path[0]||target;if(dist(mom,t)<15){mom.path.shift();t=mom.path[0]||target}let dx=t.x-mom.x,dy=t.y-mom.y,d=Math.hypot(dx,dy)||1;move(mom,dx/d*speed,dy/d*speed,dt)}
function patrolTarget(){let candidates=pidx()===1?[...tasks.filter(t=>!t.done),...(pl.history||[])]:nodes;let t=candidates[Math.floor(Math.random()*candidates.length)]||nodes[0];return{x:t.x,y:t.y}}
function momAI(dt){mom.seenCool=Math.max(0,mom.seenCool-dt);let idx=pidx(),canSee=visible();if(canSee){mom.lastSeen={x:pl.x,y:pl.y};mom.search=5+phase*1.5;if(!mom.seenCool){seen++;mom.seenCool=5;if(idx>=1)say(angry[Math.floor(Math.random()*angry.length)]);pat=Math.max(0,pat-2)}}let target,speed=P[phase].mom*(idx===0?1:idx===1?1.12:idx===2?1.3:1.65);
if(idx===3){target=canSee?pl:(mom.lastSeen||mom.investigate||mom.target);if(pl.hidden&&dist(mom,pl)<65&&Math.random()<dt*.12){pl.hidden=false;say("EU SEI QUE VOCÊ TÁ ESCONDIDO!");target=pl}follow(target||pl,speed,dt)}
else if(mom.investigate){follow(mom.investigate,speed*1.12,dt);if(dist(mom,mom.investigate)<25){mom.search-=dt;if(mom.search<=0){mom.investigate=null;mom.path=[]}}}
else if(idx>=1&&mom.lastSeen&&mom.search>0){follow(mom.lastSeen,speed,dt);if(dist(mom,mom.lastSeen)<30)mom.search-=dt;if(mom.search<=0){mom.lastSeen=null;mom.path=[]}}
else{mom.pause-=dt;if(!mom.target||dist(mom,mom.target)<22){if(mom.pause<=0){mom.target=patrolTarget();mom.path=[];mom.pause=idx===0?1+Math.random()*2:.3+Math.random()}}else follow(mom.target,speed,dt)}
if(idx===3&&!pl.hidden&&dist(pl,mom)<31)fail()}
function fail(){if(state!=="playing")return;save.caught++;saveIt();state="scolding";failStage="approach";failT=0;doing=null;$("#progressBox").style.display="none";say(scolds[Math.floor(Math.random()*scolds.length)],9);beep("alert")}
function complete(t){t.done=true;doing=null;prog=0;totalDone++;save.tasksDone++;combo=comboT>0?combo+1:1;maxCombo=Math.max(maxCombo,combo);save.bestCombo=Math.max(save.bestCombo,maxCombo);comboT=11;let gain=100*combo;score+=gain;pat=Math.min(100,pat+9);beep("done");$("#taskToast").textContent="✓ TAREFA CONCLUÍDA! +"+gain+(combo>1?" • COMBO x"+combo:"");$("#taskToast").style.display="block";$("#taskToast").classList.remove("pop");void $("#taskToast").offsetWidth;$("#taskToast").classList.add("pop");toastT=1.8;hud();if(combo>=3)achievement("broom","MESTRE DA VASSOURA");if(tasks.every(x=>x.done))finishPhase()}
function stars(){let ratio=time/P[phase].time,s=1;if(ratio>.2&&seen<=3&&alerts<=3)s=2;if(ratio>.38&&seen<=1&&alerts<=1&&score>=tasks.length*120)s=3;return s}
function finishPhase(){if(phase===2&&!finaleDone){finaleDone=true;state="finale";$("#finale").classList.add("active");$("#finaleTitle").textContent="Ufa... terminei.";$("#finaleText").textContent="...";setTimeout(()=>{if(state!=="finale")return;$("#finaleTitle").textContent="MENINOOOO!";$("#finaleText").textContent="ÚLTIMA MISSÃO";beep("alert");setTimeout(()=>{if(state!=="finale")return;let perfect=stars()===3&&alerts<=1&&score>=500;$("#finaleTitle").textContent=perfect?"FINAL PERFEITO 😂":"VEM COMER! 🍛";$("#finaleText").textContent=perfect?"Hmm... até que ficou bom. AMANHÃ TEM MAIS.":"Você sobreviveu às tarefas de casa!";$("#finaleBtn").style.display="inline-block"},1800)},1300);return}state="complete";let bonus=Math.round(time*3)+(seen===0?500:0);score+=bonus;totalScore+=score;beep("win");let st=stars();save.stars[phase]=Math.max(save.stars[phase]||0,st);save.unlocked=Math.max(save.unlocked,Math.min(3,phase+2));save.bestScore=Math.max(save.bestScore,totalScore);if(!save.bestTime||totalElapsed<save.bestTime)save.bestTime=Math.round(totalElapsed);achievement("first","PRIMEIRO DIA");if(seen<=1)achievement("ninja","NINJA DA CASA");if(st===3)achievement("exemplar","FILHO EXEMPLAR");saveIt();$("#stars").textContent="⭐".repeat(st)+"☆".repeat(3-st);$("#resultTime").textContent=fmt(time);$("#resultTasks").textContent=tasks.length+"/"+tasks.length;$("#resultScore").textContent=score;$("#resultCombo").textContent="x"+maxCombo;$("#resultAlerts").textContent=alerts;$("#resultSeen").textContent=seen;setTimeout(()=>{if(phase===2){$("#totalTime").textContent=fmt(totalElapsed);$("#totalTasks").textContent=totalDone;$("#totalScore").textContent=totalScore;show("victory");state="victory"}else show("phaseComplete")},700)}
function eventMsg(s){$("#eventToast").textContent=s;$("#eventToast").style.display="block";eventToastT=2.7}
function randomEvent(){let pressure=tasks.filter(t=>t.done).length/tasks.length, pool=["cup","phone","bell","falsealarm"];if(phase>=1)pool.push("burn","water");if(phase===2)pool.push("rain","blackout","momphone");if(pressure<.25&&pat<45)pool=pool.filter(x=>!["water","blackout"].includes(x));let e=pool[Math.floor(Math.random()*pool.length)];if(e==="cup"){eventMsg("💥 CRASH! COPO QUEBROU!");beep("alert");noiseAt(55,250,245);say("QUE BARULHO FOI ESSE?!");tempTasks.push({id:"glass",name:"Limpar o copo quebrado",x:250,y:245,d:2.5,icon:"💥",act:"Limpando cacos...",temp:true,done:false,deadline:14})}
if(e==="phone"){event={type:"phone",x:pl.x,y:pl.y,t:6};eventMsg("📱 CELULAR TOCANDO! [E] para desligar");beep("ring")}
if(e==="bell"){eventMsg("🔔 CAMPAINHA! A mãe foi atender.");beep("bell");mom.investigate={x:35,y:350};mom.search=7}
if(e==="burn"){event={type:"burn",x:855,y:385,t:9};eventMsg("⚠ A COMIDA TÁ QUEIMANDO! Vá ao fogão!");beep("alert")}
if(e==="rain"){rain=true;event={type:"rain",t:8};eventMsg("🌧 CHUVA NO QUINTAL!");beep("bell")}
if(e==="water"){event={type:"water",x:730,y:430,t:13};tempTasks.push({id:"water",name:"Secar o chão",x:730,y:430,d:2.5,icon:"💧",act:"Secando...",temp:true,done:false,deadline:13});eventMsg("💧 ÁGUA DERRAMADA!")}
if(e==="blackout"){blackout=8;event={type:"blackout",x:600,y:250,t:8};$("#blackout").classList.add("on");eventMsg("⚡ FALTOU ENERGIA!");say("AGORA PRONTO!")}
if(e==="momphone"){momPhone=6;event={type:"momphone",t:6};eventMsg("📞 O telefone da mãe tocou!");say("Alô? Fala, comadre...")}
if(e==="falsealarm"){let q=nodes[Math.floor(Math.random()*nodes.length)];event={type:"falsealarm",x:q.x,y:q.y,t:5};mom.investigate={x:q.x,y:q.y};mom.search=5;eventMsg("❓ BARULHO EM OUTRO CÔMODO");say("QUE FOI ISSO?")}}
function eventUpdate(dt){if(!event)return;event.t-=dt;if(event.type==="phone"){noiseAt(dt*5,event.x,event.y);if(K.e&&dist(pl,event)<65){eventMsg("📱 Celular desligado a tempo!");event=null;return}if(event.t<=0){pat=Math.max(0,pat-8);say("EU TÔ OUVINDO ESSE CELULAR!");event=null}}
else if(event.type==="burn"){if(K.e&&dist(pl,event)<75){eventMsg("🍳 Ufa! Salvou a comida.");event=null;return}if(event.t<=0){pat=Math.max(0,pat-10);noiseAt(40,event.x,event.y);say("TÁ CHEIRANDO QUEIMADO!");event=null}}
else if(event.type==="rain"&&event.t<=0){rain=false;event=null}
else if(event.type==="blackout"){if(K.e&&dist(pl,event)<60){blackout=0;$("#blackout").classList.remove("on");eventMsg("⚡ Energia religada! +100");score+=100;event=null}else if(event.t<=0){blackout=0;$("#blackout").classList.remove("on");event=null}}
else if(event.type==="momphone"&&event.t<=0){momPhone=0;event=null}
else if(event.type==="falsealarm"&&event.t<=0)event=null
else if(event.type==="water"&&event.t<=0)event=null}
}
function countUpdate(dt){if(!count)return;callT-=dt;if(callT<=0){if(count===1){count=2;say("DOIS...",1.2)}else if(count===2){count=3;say("DOIS E MEIO...",1.1)}else{count=0;say("TRÊS!",1.3);pat=Math.max(0,pat-7)}}}
function startCount(){count=1;say("UM...",1.1)}
function nearList(list,rad=48){let b=null,d=rad;for(const o of list){if(o.done||picked.has(o.id)||usedHelp.has(o.id))continue;let q=dist(pl,o);if(q<d){b=o;d=q}}return b}
function interact(dt){let nt=nearTask(),nh=nearHide(),tt=nearList(tempTasks,60),ot=nearList(optionalTasks,60),tool=nearList(tools,45),help=nearList(helps,45),obj=nearList(interactives.filter(x=>!secretUsed.has(x.id)),52);nt=tt||ot||nt;if(pl.hidden){$("#interaction").style.display="block";$("#interaction").textContent="[E] SAIR DO ESCONDERIJO";if(K.e&&!pl.eLock){pl.hidden=false;pl.eLock=true}return}
let need=nt&&req[nt.id]&&equipped!==req[nt.id],label=tool?"[E] PEGAR "+tool.name:help?"[E] USAR "+help.name:obj?"[E] "+obj.name:nt?(need?"PRECISA: "+itemNames[req[nt.id]]:"[E] "+(nt.short||nt.name.toUpperCase())):nh?"[E] ESCONDER — "+nh.label:"";$("#interaction").style.display=label?"block":"none";if(label)$("#interaction").textContent=label;
if(K.e&&tool&&!pl.eLock){equipped=tool.id;picked.add(tool.id);pl.eLock=true;eventMsg(tool.icon+" "+tool.name+" equipado!");hud();return}
if(K.e&&help&&!pl.eLock){usedHelp.add(help.id);energy=Math.min(100,energy+(help.e||0));time+=help.time||0;pl.eLock=true;eventMsg(help.icon+" "+help.name+" usado!");return}
if(K.e&&obj&&!pl.eLock){pl.eLock=true;secretUsed.add(obj.id);if(obj.kind==="distract"){distraction=2.5;energy=Math.min(100,energy+18);say(obj.id==="tv"?"VIDEOGAME AGORA?":"Depois reclama que não deu tempo!");pat=Math.max(0,pat-4);eventMsg("😴 Você perdeu alguns segundos...")}else if(obj.kind==="secret"){score+=100;eventMsg("✨ +100 PONTOS SECRETOS!")}else if(obj.kind==="water"&&equipped==="bucket"){let b=tasks.find(t=>t.id==="bath");if(b){b.filled=true;eventMsg("🪣 Balde cheio!")}}else eventMsg("🥶 Só olhando a geladeira não resolve.");return}
if(K.e&&nh&&!nt&&!pl.eLock){pl.hidden=true;pl.eLock=true;pl.x=nh.x;pl.y=nh.y;doing=null;$("#progressBox").style.display="none";return}
if(K.e&&nt&&!need){if(nt.id==="bath"&&!nt.filled){eventMsg("🪣 Encha o balde na pia primeiro!");return}if(doing!==nt){doing=nt;prog=0}let slow=rain&&nt.id==="yard"?.55:1;prog+=dt*slow;noise=Math.min(100,noise+dt*4);if(Math.random()<dt*7)spawn(nt.x,nt.y,nt.id==="dishes"||nt.id==="bath"?"#d9fbff":"#d7c49a",nt.id==="cook"?1:2);$("#progressBox").style.display="block";$("#progressText").textContent=nt.act+(rain&&nt.id==="yard"?" (chuva!)":"");$("#progressBar").style.width=Math.min(100,prog/nt.d*100)+"%";if(prog>=nt.d){if(nt.optional){nt.done=true;score+=300;eventMsg("⭐ OBJETIVO BÔNUS +300");doing=null;prog=0}else if(nt.temp){nt.done=true;score+=150;eventMsg("✓ IMPREVISTO RESOLVIDO +150");doing=null;prog=0}else complete(nt)}}else{doing=null;prog=0;$("#progressBox").style.display="none";let done=nearTask(true);if(done&&done.done){revisitT+=dt;if(revisitT>2.5){say("Agora quer limpar duas vezes?");revisitT=-8}}else revisitT=0}}
function update(dt){updateParticles(dt);if(achT>0&&(achT-=dt)<=0)$("#achievementToast").style.display="none";if(toastT>0&&(toastT-=dt)<=0)$("#taskToast").style.display="none";if(eventToastT>0&&(eventToastT-=dt)<=0)$("#eventToast").style.display="none";if(state==="playing"){if(distraction>0){distraction-=dt;time-=dt;hud();return}if(slip>0){slip-=dt}totalElapsed+=dt;time-=dt;pat=Math.max(0,pat-P[phase].drain*dt);noise=Math.max(0,noise-dt*13);comboT=Math.max(0,comboT-dt);if(!comboT)combo=0;callT=Math.max(0,callT-dt);if(count)countUpdate(dt);nextCall-=dt;if(nextCall<=0&&!count){let pool=pidx()>=2?angry:calls,s=pool[Math.floor(Math.random()*pool.length)];say(s);if(s.includes("contar até três"))setTimeout(()=>{if(state==="playing")startCount()},2100);nextCall=10+Math.random()*12}
eventT-=dt;if(eventT<=0&&!event){randomEvent();let bad=pat<35?1.45:tasks.filter(t=>t.done).length/tasks.length>.7?.82:1;eventT=P[phase].event*bad*(.8+Math.random()*.5)}eventUpdate(dt);for(const t of tempTasks)if(!t.done&&t.deadline!=null){t.deadline-=dt;if(t.deadline<=0){t.done=true;pat=Math.max(0,pat-8);say("E ISSO AQUI?")}}
if(phase===2&&!surpriseAdded&&tasks.filter(t=>t.done).length>=3&&Math.random()<dt*.08){surpriseAdded=true;let x={...T.trash,id:"extraTrash",name:"Surpresa: jogar o lixo fora",temp:true,done:false};tempTasks.push(x);eventMsg("📋 NOVA TAREFA! JOGA O LIXO FORA TAMBÉM!");say("Ah! E antes que eu esqueça...")}

let dx=slip>0?0:(K.ArrowRight||K.d?1:0)-(K.ArrowLeft||K.a?1:0),dy=(K.ArrowDown||K.s?1:0)-(K.ArrowUp||K.w?1:0),running=(K.Shift&&energy>1&&(dx||dy)&&!pl.hidden);pl.moving=!!(dx||dy)&&!pl.hidden;if(pl.moving){stillT=0;let d=Math.hypot(dx,dy);dx/=d;dy/=d;if(Math.abs(dx)>Math.abs(dy))pl.dir=dx>0?"right":"left";else pl.dir=dy>0?"down":"up";let sp=pl.speed*(running?1.55:1);move(pl,dx*sp,dy*sp,dt);pl.history=pl.history||[];if(!pl.histT||((pl.histT-=dt)<=0)){pl.history.unshift({x:pl.x,y:pl.y});pl.history=pl.history.slice(0,4);pl.histT=2}if(running){energy=Math.max(0,energy-dt*28);noise=Math.min(100,noise+dt*22);runT+=dt;if(runT>4.5){say("PARA DE CORRER DENTRO DE CASA!");runT=-10}stepT-=dt;if(stepT<=0){beep(running?"run":"step");stepT=running?.18:.32;if(running)spawn(pl.x,pl.y+18,"#d9c59b",2)}}}else{energy=Math.min(100,energy+dt*11);runT=Math.max(0,runT-dt)}}else{energy=Math.min(100,energy+dt*15);stillT+=dt;if(stillT>9){say("Tá esperando o serviço se fazer sozinho?");stillT=-12}}
if(event&&event.type==="water"&&running&&dist(pl,event)<45&&Math.random()<dt*.35){slip=.65;eventMsg("💦 ESCORREGOU!");}interact(dt);if(momPhone<=0)momAI(dt);let close=dist(pl,mom)<115&&pidx()>=2;$("#dangerVignette").classList.toggle("on",close);if(pat<=18&&!red){red=true;alerts++;beep("alert");$("#alert").style.display="block";$("#canvasWrap").classList.add("shake");setTimeout(()=>{$("#alert").style.display="none";$("#canvasWrap").classList.remove("shake")},2100)}if(time<=0)fail();hud()}
else if(state==="scolding"){let d=dist(pl,mom);if(failStage==="approach"){if(d>47)follow(pl,140,dt);else{failStage="lecture";failT=2.7}}else if((failT-=dt)<=0){$("#scoldText").textContent=call;$("#overTasks").textContent=tasks.filter(t=>t.done).length+"/"+tasks.length;$("#overScore").textContent=score;$("#overTime").textContent=fmt(P[phase].time-time);$("#overCombo").textContent="x"+maxCombo;show("gameOver");state="over"}}}
function spawn(x,y,c,n=4){for(let i=0;i<n;i++)if(particles.length<70)particles.push({x,y,vx:(Math.random()-.5)*28,vy:-8-Math.random()*18,t:.5+Math.random()*.3,c})}
function updateParticles(dt){for(let i=particles.length-1;i>=0;i--){let p=particles[i];p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=22*dt;p.t-=dt;if(p.t<=0)particles.splice(i,1)}}
function drawParticles(){for(const p of particles){X.globalAlpha=Math.max(0,p.t);X.fillStyle=p.c;X.beginPath();X.arc(p.x,p.y,2.5,0,7);X.fill()}X.globalAlpha=1}
function rr(x,y,w,h,r,f,s){X.beginPath();X.roundRect(x,y,w,h,r);if(f){X.fillStyle=f;X.fill()}if(s){X.strokeStyle=s;X.lineWidth=2;X.stroke()}}
function room(x,y,w,h,n,c,t){X.fillStyle=c;X.fillRect(x,y,w,h);X.save();X.globalAlpha=.09;X.strokeStyle="#243044";for(let yy=y+12;yy<y+h;yy+=t==="tile"?28:24){X.beginPath();X.moveTo(x,yy);X.lineTo(x+w,yy);X.stroke()}if(t==="tile")for(let xx=x;xx<x+w;xx+=28){X.beginPath();X.moveTo(xx,y);X.lineTo(xx,y+h);X.stroke()}X.restore();rr(x+10,y+8,Math.max(72,n.length*8),24,8,"#ffffffb8");X.fillStyle="#243044";X.font="bold 12px sans-serif";X.fillText(n,x+19,y+25)}
function furniture(f){X.save();X.shadowColor="#0004";X.shadowBlur=5;X.shadowOffsetY=3;rr(f.x,f.y,f.w,f.h,7,f.c,"#27364a");X.shadowColor="transparent";if(f.k==="sofa"){rr(f.x+8,f.y+9,f.w-16,25,7,"#63a8d1");X.strokeStyle="#d6efff";X.beginPath();X.moveTo(f.x+f.w/2,f.y+10);X.lineTo(f.x+f.w/2,f.y+34);X.stroke()}if(f.k==="bed"){rr(f.x+10,f.y+8,f.w-20,f.h-16,6,"#f6dfbd");rr(f.x+18,f.y+10,50,24,6,"#fff");X.fillStyle=f.c;X.fillRect(f.x+10,f.y+45,f.w-20,25)}if(f.k==="stove"){X.fillStyle="#222";for(const dx of[22,65])for(const dy of[16,36]){X.beginPath();X.arc(f.x+dx,f.y+dy,7,0,7);X.fill()}if((doing&&doing.id==="cook")||(event&&event.type==="burn")){X.fillStyle="#ff5a30";X.beginPath();X.arc(f.x+65,f.y+34,7+Math.sin(performance.now()/80)*3,0,7);X.fill()}}if(f.k==="sink"){X.fillStyle="#d8f4f1";X.beginPath();X.ellipse(f.x+45,f.y+21,28,12,0,0,7);X.fill()}if(f.k==="toilet"){X.fillStyle="#fff";X.beginPath();X.ellipse(f.x+24,f.y+38,17,23,0,0,7);X.fill()}X.restore()}
function dirty(id){return tasks.some(t=>t.id===id&&!t.done)}
function doors(){const ds=[[320,153,14,62],[640,118,14,62],[320,380,14,65],[640,380,14,65],[449,285,66,14],[759,285,66,14]];for(const d of ds){X.fillStyle="#6d4029";X.fillRect(...d);X.fillStyle="#d99a5c";if(d[2]<d[3])X.fillRect(d[0]+3,d[1]+3,7,d[3]-6);else X.fillRect(d[0]+3,d[1]+3,d[2]-6,7)}}
function decor(){rr(78,160,175,72,10,"#e45757aa");rr(85,168,160,48,8,"#f07a70");rr(235,62,55,34,5,"#263238");rr(225,98,75,16,4,"#79523c");X.fillStyle="#fff7d0";X.fillRect(38,65,35,28);X.fillRect(250,130,35,25);X.fillStyle="#86d4ef";X.fillRect(241,68,43,22);X.strokeStyle="#444";X.lineWidth=3;X.beginPath();X.arc(278,270,19,0,7);X.stroke();X.beginPath();X.moveTo(278,289);X.lineTo(278,325);X.stroke();if(dirty("sweep")){X.fillStyle="#9b765a";for(const p of[[55,245],[225,190],[275,335],[90,340]]){X.beginPath();X.arc(p[0],p[1],5,0,7);X.fill()}}if(dirty("toys")||dirty("organize")){X.font="22px serif";X.fillText("🧸",520,225);X.fillText("⚽",590,240);X.fillText("👕",440,235)}X.font="18px serif";X.fillText("🧴",900,230);X.fillText("🪣",860,240);X.fillText("🪞",760,120);X.fillText("🧼",735,240);if(dirty("bath")){X.fillStyle="#8c8b6870";for(const p of[[790,220],[880,190],[760,250],[900,150]]){X.beginPath();X.ellipse(p[0],p[1],12,6,.3,0,7);X.fill()}}rr(785,390,120,42,7,"#d7a86e");X.font="18px serif";X.fillText("🥕",805,418);X.fillText("🍅",840,418);X.fillText("🥘",880,418);X.font="19px serif";if(dirty("dishes")||dirty("kitchen"))X.fillText("🍽️🍽️🍽️",755,450);X.strokeStyle="#5b7350";X.beginPath();X.moveTo(35,420);X.lineTo(295,420);X.stroke();X.font="20px serif";X.fillText("👕",85,448);X.fillText("🩳",160,448);X.fillText("🪣",200,535);X.fillText("🧹",255,545);X.fillText("🌿",70,565);X.fillText("🌱",145,555);X.fillStyle="#6b4d32";X.fillRect(35,470,22,70);X.fillStyle="#4d9b50";X.beginPath();X.arc(46,460,35,0,7);X.fill();if(dirty("yard")){X.font="17px serif";for(const p of[[70,520],[130,550],[175,485],[295,510]])X.fillText("🍂",p[0],p[1])}if(rain){X.strokeStyle="#70b9e8aa";X.lineWidth=2;for(let i=0;i<30;i++){let x=20+(i*47)%300,y=(performance.now()/5+i*31)%180+400;X.beginPath();X.moveTo(x,y);X.lineTo(x-5,y+10);X.stroke()}}}
function taskDraw(t,n){if(t.done)return;let p=3+Math.sin(performance.now()/220)*3;X.strokeStyle=n===t?"#fff36b":"#ffd34e";X.lineWidth=n===t?5:3;X.setLineDash([7,5]);X.beginPath();X.arc(t.x,t.y,24+p,0,7);X.stroke();X.setLineDash([]);X.font="25px serif";X.textAlign="center";X.fillText(t.icon,t.x,t.y+8);X.textAlign="left"}
function kid(){let p=pl,running=K.Shift&&p.moving&&energy>0,b=p.moving?Math.sin(p.walk*(running?1.55:1))*2.5:Math.sin(performance.now()/500)*.7,sw=Math.sin(p.walk*(running?1.6:1))*5;X.save();X.globalAlpha=p.hidden?.32:1;X.translate(p.x,p.y+b);if(running)X.rotate((p.dir==="left"?-1:p.dir==="right"?1:0)*.08);X.fillStyle="#0003";X.beginPath();X.ellipse(0,18,15,6,0,0,7);X.fill();X.strokeStyle="#24252a";X.lineWidth=5;X.beginPath();X.moveTo(-5,9);X.lineTo(-7+(p.moving?sw:0),20);X.moveTo(5,9);X.lineTo(7-(p.moving?sw:0),20);X.stroke();X.strokeStyle="#f2b98b";X.beginPath();X.moveTo(-9,-2);X.lineTo(-15-(p.moving?sw*.5:0),8);X.moveTo(9,-2);X.lineTo(15+(p.moving?sw*.5:0),8);X.stroke();rr(-11,-10,22,23,7,"#2d8dcc","#18364d");X.fillStyle="#f2b98b";X.beginPath();X.arc(0,-20,11,0,7);X.fill();X.fillStyle="#35271f";X.beginPath();X.arc(0,-25,11,3.2,6.3);X.lineTo(9,-19);X.lineTo(0,-20);X.lineTo(-5,-25);X.fill();X.fillStyle="#26324b";X.fillRect(-10,19,8,5);X.fillRect(3,19,8,5);X.fillStyle="#fff";X.fillRect(-11,22,10,3);X.fillRect(2,22,10,3);X.restore()}
function mother(){let i=pidx(),b=Math.sin(mom.walk)*1.5;X.save();X.translate(mom.x,mom.y+b);X.fillStyle="#0003";X.beginPath();X.ellipse(0,19,17,6,0,0,7);X.fill();X.strokeStyle="#54382d";X.lineWidth=5;X.beginPath();X.moveTo(-6,10);X.lineTo(-7,22);X.moveTo(6,10);X.lineTo(7,22);X.stroke();X.strokeStyle="#d99570";X.beginPath();X.moveTo(-11,-3);X.lineTo(-17,8);X.moveTo(11,-3);X.lineTo(17,i>=2?-3:8);X.stroke();rr(-13,-11,26,26,8,i===3?"#d52e4c":"#e35d7a","#7a2941");X.fillStyle="#d99570";X.beginPath();X.arc(0,-23,12,0,7);X.fill();X.fillStyle="#4a2e24";X.beginPath();X.arc(0,-27,13,3.1,6.3);X.arc(10,-28,7,0,7);X.fill();X.fillStyle="#222";X.font="bold 24px sans-serif";X.textAlign="center";if(i===1)X.fillText("?",0,-46);if(i===2)X.fillText("!",0,-46);if(i===3)X.fillText("!!!",0,-46);X.restore();X.textAlign="left"}
function bubble(s,big=false){big=big||pidx()===3;let w=big?360:310,h=big?66:50,x=Math.max(8,Math.min(W-w-8,mom.x-w/2)),y=Math.max(8,mom.y-(big?105:88));rr(x,y,w,h,13,pidx()>=2?"#fff0e8":"#fff",pidx()>=2?"#d64a42":"#27364a");X.fillStyle="#202635";X.font=(big?"bold 17px":"bold 14px")+" sans-serif";X.textAlign="center";let words=s.split(" "),line="",lines=[];for(const word of words){if(X.measureText(line+word).width>w-28){lines.push(line);line=""}line+=word+" "}lines.push(line);lines.slice(0,2).forEach((l,i)=>X.fillText(l,x+w/2,y+22+i*20));X.textAlign="left"}
function draw(){if(!["playing","scolding","complete","paused","finale"].includes(state))return;X.clearRect(0,0,W,H);room(18,18,302,362,"SALA","#f5d98a","wood");room(334,18,306,267,"QUARTO","#efc7d4","wood");room(654,18,288,267,"BANHEIRO","#bfe7ec","tile");room(654,299,288,283,"COZINHA","#cfe8c4","tile");room(334,299,306,283,"QUARTO","#ddc9e9","wood");room(18,394,302,188,"ÁREA / QUINTAL","#9ed08b","tile");decor();doors();X.fillStyle="#694b39";walls.forEach(q=>X.fillRect(q.x,q.y,q.w,q.h));furn.forEach(furniture);X.font="22px serif";for(const o of tools)if(!picked.has(o.id))X.fillText(o.icon,o.x-10,o.y+7);for(const o of helps)if(!usedHelp.has(o.id))X.fillText(o.icon,o.x-10,o.y+7);let n=state==="playing"?nearTask():null;[...tasks,...tempTasks,...optionalTasks].forEach(t=>taskDraw(t,n));drawParticles();hides.forEach(h=>{X.strokeStyle="#8ce6ff88";X.setLineDash([3,5]);X.strokeRect(h.x-17,h.y-17,34,34);X.setLineDash([])});kid();mother();if(callT>0||state==="scolding"&&failStage==="lecture")bubble(call,state==="scolding")}
function loop(ts){let dt=Math.min(.033,(ts-last)/1000||0);last=ts;update(dt);draw();requestAnimationFrame(loop)}
addEventListener("keydown",e=>{let k=e.key.length===1?e.key.toLowerCase():e.key;if(k==="q"&&state==="playing"&&equipped){eventMsg("📦 "+itemNames[equipped]+" largado.");equipped=null;hud();}if(k==="Escape"&&(state==="playing"||state==="paused")){togglePause();e.preventDefault();return}K[k]=true;if(["ArrowUp","ArrowDown","ArrowLeft","ArrowRight"," "].includes(e.key))e.preventDefault()});
addEventListener("keyup",e=>{let k=e.key.length===1?e.key.toLowerCase():e.key;K[k]=false;if(k==="e"&&pl)pl.eLock=false});
function togglePause(){if(state==="playing"){state="paused";$("#pause").classList.add("active")}else if(state==="paused"){state="playing";$("#pause").classList.remove("active")}}
$("#finaleBtn").onclick=()=>{$("#finale").classList.remove("active");$("#finaleBtn").style.display="none";state="playing";finishPhase()};$("#introBtn").onclick=()=>{$("#intro").classList.remove("active");if(!save.tutorial){$("#tutorial").classList.add("active")}else beginPhase(pendingPhase)};$("#tutorialBtn").onclick=()=>{save.tutorial=true;saveIt();$("#tutorial").classList.remove("active");beginPhase(pendingPhase)};$("#playBtn").onclick=()=>{totalElapsed=totalDone=totalScore=0;start(0)};$("#selectBtn").onclick=()=>{menuData();show("phaseSelect")};$("#howBtn").onclick=()=>show("how");$("#settingsBtn").onclick=()=>{audioUI();show("settings")};$("#musicBtn").onclick=()=>{save.music=!save.music;saveIt();audioUI()};$("#sfxBtn").onclick=()=>{save.sfx=!save.sfx;saveIt();audioUI()};$("#volumeRange").oninput=e=>{save.volume=+e.target.value/100;saveIt()};document.querySelectorAll(".backMenu").forEach(b=>b.onclick=()=>{menuData();show("menu")});$("#nextBtn").onclick=()=>start(phase+1);$("#retryBtn").onclick=()=>start(phase);$("#menuBtn").onclick=$("#victoryMenuBtn").onclick=()=>{state="menu";menuData();show("menu")};$("#resumeBtn").onclick=togglePause;$("#restartPauseBtn").onclick=()=>start(phase);$("#pauseMenuBtn").onclick=()=>{$("#pause").classList.remove("active");state="menu";menuData();show("menu")};menuData();requestAnimationFrame(loop);
})();